spring:
  application:
    name: Configuracion-Inicial
  mvc:
    pathmatch:
      matching-strategy=ant-path-matcher:
  jpa: # Mostrar las consultas SQL en el log (opcional, pero útil para depuración)
    show-sql: true
    hibernate: # Configuración JPA/Hibernate para la generación automática de esquema
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource: #Configuración de PostgreSQL
    url: jdbc:postgresql://localhost:5432/db_codelab
    username: codelab
    password: Lovelace
server:
  port: 15467

